1712
ngageoint/hootenanny-ui pull request #1716
Opened 2020-01-27 19:28 UTC by jackgrossman18

ref #1712

2020-01-30 14:25 UTC, maxgrossman commented on modules/Hoot/ui/sidebar/advancedOpts.js
> +                                    .append('div')
![image](https://user-images.githubusercontent.com/15100429/73457604-e6a91f80-4341-11ea-9a4d-df94dade49cd.png)

There seems to be a state in which having 2 dropdowns open leads to adding divs over and over if you click on one of the info buttons.

I think we can avoid this if we don't append on click, but show a div that we add in the same way we do this button  (d3 data binding cycle).

More succinctly I think you...

1. add the description div not in the callback, but right underneath were 339 following d3 data binding flow
2. add a class for hiddenn to the div (there should be one we have already in the ui), if not, a display = none
3. then in the callback, all you do is set the value of the class/display property that shows/hides the div as the inverse of what it is `selection.classed('name-of-class, !selection.classed('name-of-class')`

2020-01-30 14:27 UTC, maxgrossman commented on css/80_app.css
> +        border: 1px solid #ccc;
I think it looks fine without the border. adding the border creates the appearance of a double :rainbow:, oops i mean border!

2020-01-30 14:30 UTC, maxgrossman requested changes
See the comments above.

2020-01-30 16:05 UTC, jackgrossman18 commented
@maxgrossman requested changes made

2020-01-30 22:16 UTC, maxgrossman commented
This is some serious nitpick, sorry, but I also noticed that "active" css is being applied at times when we might not expect it to. 

I think maybe we could only apply a tint to the background color "on hover"
![hover_css](https://user-images.githubusercontent.com/15100429/73495240-255fc980-4384-11ea-9498-c705d93d65a5.gif)
.

2020-02-04 20:40 UTC, jackgrossman18 commented
@maxgrossman

2020-02-05 17:48 UTC, jackgrossman18 commented
@maxgrossman ready to merge :sun_with_face:

2020-02-05 21:46 UTC, maxgrossman approved these changes
:cake:

2020-02-05 21:46 UTC, merged