1769
ngageoint/hootenanny-ui pull request #1779
Opened 2020-05-05 16:40 UTC by jackgrossman18

ref #1769

2020-05-19 22:00 UTC, brianhatchl requested changes

2020-05-19 22:00 UTC, brianhatchl commented on modules/ui/tag_link_url.js
> +            .attr('title', t('icons.open_link'))
We need to add the value for `icons.open_link` to core.yaml

2020-05-19 22:00 UTC, brianhatchl commented on modules/ui/raw_tag_editor.js
> +                row.select('button.remove');   // propagate bound data
Not sure if we need this or can just call
`row.call(reference)`

the difference in syntax might be where this was plucked from iD `v2.14.`3 and hoot-ui is only on iD `v2.12.1`

2020-05-19 22:00 UTC, brianhatchl commented on modules/ui/raw_tag_editor.js
> +            }
When a new tag is added with a url value, this code is invoked, but it doesn't remove or update the existing tag copy button, leading to the ui appear like this:

![Screenshot from 2020-05-19 17-33-57](https://user-images.githubusercontent.com/2600932/82382645-5418b300-99fa-11ea-8c7b-7bd78762db94.png)

When an existing feature with a url tag is selected (or another feature is selected and this feature then re-selected) the tag table renders fine.

2020-05-20 15:37 UTC, jackgrossman18 commented on modules/ui/raw_tag_editor.js
> +                row.select('button.remove');   // propagate bound data
in testing removing body from line 188, it results in empty row

![remove_body](https://user-images.githubusercontent.com/25868208/82466313-3d23a080-9a8e-11ea-8905-2ecf7aacb176.png)

2020-05-20 20:45 UTC, brianhatchl commented on modules/ui/raw_tag_editor.js
> +
remove if not needed

2020-05-20 20:45 UTC, brianhatchl commented on modules/ui/raw_tag_editor.js
>                  row.call( select );
Should call this after other button types or move checkmark above column

![image](https://user-images.githubusercontent.com/2600932/82495618-5e4db680-9ab9-11ea-93e3-13f4db9d108d.png)

2020-05-21 14:57 UTC, brianhatchl commented
The border radius needs to be moved to the tag copy button
![image](https://user-images.githubusercontent.com/2600932/82572064-dd8ec900-9b51-11ea-996d-cf6f5f07802c.png)

2020-05-21 17:52 UTC, brianhatchl approved these changes

2020-05-21 17:52 UTC, merged