Open Hoot-UI data in josm
ngageoint/hootenanny-ui pull request #1984
Opened 2022-08-18 01:02 UTC by mzagorskirs

Related Jira tickets:
- [VGI-3361]
- [VGI-3401]

Demos:

https://user-images.githubusercontent.com/43011672/185269317-f863eab0-ce0b-4686-9b56-9590bbbc8648.mp4
https://user-images.githubusercontent.com/43011672/185269322-81c8f934-578a-4114-812f-5c2c2b877b52.mp4

2022-08-18 01:09 UTC, mzagorskirs commented
Note: I will be updating the icon used in the modal.

2022-08-22 15:15 UTC, mzagorskirs commented
Note: since this mechanism temporarily downloads the data first then deletes after alerting JOSM that there is a file to load, I'm not satisfied that this is the best approach.  I plan to look into utilizing JOSM's `import` API endpoint.

2022-08-31 18:03 UTC, brianhatchl commented
I don't think there needs to be an export dialog at all for `Open in JOSM`.  Assume `include hoot tags` is true.

When the file download gets replaced by the remote control /import call, the url needs to looks something like
>http://127.0.0.1:8111/import?headers=Cookie,SESSION=eefcc756-4041-445f-a605-4ad78371bda9&url=https://localhost:8080/hoot-services/job/export/ex_65d5dfb9d78c4e7c9f141dd4a6efd466?outputname=Starbucks.osm.zip

I put together a test example in another branch by adding an action button to the Export jobs in the Jobs panel here https://github.com/ngageoint/hootenanny-ui/blob/85008687fd56f97499035ddc10da152889e4439f/modules/Hoot/managers/api.js#L982-L1000

2022-09-06 21:25 UTC, brianhatchl requested changes

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/managers/api.js
> +                    outputtype: 'OSM',
make this lowercase `osm`

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/managers/api.js
> +                            await this.openDatasetInJosm(this.jobId, data.outputname + '.OSM', data.outputname);
make this lowercase `.osm`

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/config/domMetadata.js
> +
this can be reverted if no other changes to file

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/managers/api.js
> +    }
this is identical to `exportDataset` so should just use that below

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/managers/api.js
> +    }
these aren't really api methods, so would be better scoped as functions under `openDataInJosm`

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/ui/modals/exportData.js
>                      //Hoot.api.openDatasetInJosm( this.jobId, data.outputname + '.' + data.outputtype );
We should delete these two lines, they were just a placeholder when I was testing.

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/ui/managePanel/jobs.js
> +                        title: 'open in JOSM',
the tooltip convention I have going in the jobs panel is for them to be all lowercase, so this wasn't a typo

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/managers/api.js
> +                this.openInJosm(data)
could just use `exportData`

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/managers/api.js
> +    openDatasetInJosm( id, name, outputName ) {
this signature would feel better to me as `(id, name, ext)` and then the ext could be appended on line 996 below.

2022-09-06 21:25 UTC, brianhatchl commented on modules/Hoot/managers/api.js
>                      + `&url=${this.detect.origin}${this.baseUrl}/job/export/${id}?outputname=${name}.zip`
outputname=${name}.${ext}.zip

2022-09-06 22:16 UTC, brianhatchl approved these changes
LGTM :poultry_leg: :waffle:

2022-09-07 14:06 UTC, merged