Post conflation review table update
ngageoint/hootenanny-ui pull request #2044
Opened 2023-03-09 20:46 UTC by jackgrossman18

ref #1967

2023-03-10 13:32 UTC, maxgrossman reviewed
looks good to me.
tagging hatchl since he was original person thinking about solution here.

2023-03-10 14:11 UTC, brianhatchl commented
I think we need to check the `hoot:status` tag of the two features because it is mostly but not always Reference vs Secondary.
https://github.com/ngageoint/hootenanny-ui/issues/1967#issuecomment-1146168847

2023-03-15 19:32 UTC, brianhatchl requested changes

2023-03-15 19:32 UTC, brianhatchl commented on modules/Hoot/ui/conflicts/info.js
> +
I think this chunk can be removed now that `filterHootStatus` is there.

2023-03-16 13:52 UTC, brianhatchl approved these changes

2023-03-16 19:58 UTC, merged